services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - FNS_API_TOKEN=${FNS_API_TOKEN}
      - SESSION_KEY=${SESSION_KEY:-mini-budget-secret-key-change-in-production}
      - PORT=3000
    restart: unless-stopped 